In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [10]:
#from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original')

In [12]:
mnist.target

array([ 0.,  0.,  0., ...,  9.,  9.,  9.])

In [14]:
from sklearn.model_selection import train_test_split
# test_size: what proportion of original data is used for test set
X_train, X_test, y_train, y_test = train_test_split( mnist.data, mnist.target, test_size=1/7.0, random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit on training set only.
scaler.fit(X_train)
# Apply transform to both the training set and the test set.
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

C:\Users\Akshat\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [17]:
from sklearn.decomposition import PCA
# Make an instance of the Model
pca = PCA(0.95)

In [18]:
model=pca.fit(X_train)

In [21]:
model.n_components_

330

In [23]:
X_train.shape

(60000, 784)

In [24]:
X_train = model.transform(X_train)
X_test = model.transform(X_test)

In [25]:
X_train.shape

(60000, 330)

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [28]:
lr=LogisticRegression(solver = 'lbfgs')
rf=RandomForestClassifier(n_estimators=30,n_jobs=-1)

In [31]:
lr_model=lr.fit(X_train,y_train)
rf_model=rf.fit(X_train,y_train)

In [32]:
lr_pred=lr_model.predict(X_test)
rf_pred=rf_model.predict(X_test)

In [33]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,roc_auc_score,roc_curve

array([[ 914,    0,    1,    3,    2,    3,    8,    1,    3,    1],
       [   0, 1123,    9,    2,    2,    5,    2,    3,   15,    2],
       [   3,   10,  883,   19,   13,    2,   15,   12,   22,    3],
       [   2,    9,   26,  937,    0,   26,    2,    7,   19,   10],
       [   3,    4,    4,    0,  885,    3,    9,    3,    7,   30],
       [  11,    6,    9,   32,   15,  800,   15,    5,   17,   11],
       [   3,    1,    5,    0,    2,   11,  985,    0,    4,    2],
       [   6,    3,   16,    2,   12,    2,    0,  950,    1,   37],
       [   4,   23,   10,   24,    9,   24,   11,    5,  850,   18],
       [   8,    3,    5,   20,   39,   10,    0,   26,    7,  874]], dtype=int64)

array([[ 915,    0,    2,    4,    0,    2,    9,    2,    2,    0],
       [   0, 1123,   14,    9,    1,    1,    6,    4,    3,    2],
       [  10,    0,  916,   20,    7,    2,   13,    5,    9,    0],
       [   5,    5,   21,  954,    0,   15,    1,   13,   18,    6],
       [   1,    3,   18,    2,  890,    0,    7,    5,    5,   17],
       [  10,    0,   13,   35,    8,  809,   13,    7,   18,    8],
       [   6,    0,    9,    0,    3,   10,  982,    0,    3,    0],
       [   4,    3,   18,    4,   20,    1,    0,  944,    1,   34],
       [   5,    9,   16,   27,    7,   40,    7,    7,  850,   10],
       [   4,    3,   10,   16,   42,    6,    1,   38,    7,  865]], dtype=int64)

In [36]:
def AUC(result,prediction):
    fpr, tpr, thresholds = roc_curve(y_test, result.predict_proba(X_test)[:,1])
    f_rf_roc_auc=roc_auc_score(y_test,prediction)
    plt.figure()
    plt.plot(fpr, tpr, label='Classification (area = %0.2f)' % f_rf_roc_auc)
    plt.plot([0, 1], [0, 1],'r--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.legend(loc="lower right")

In [38]:
accuracy_score(y_test,lr_pred)

0.92010000000000003

In [39]:
accuracy_score(y_test,rf_pred)

0.92479999999999996

In [41]:
pca.score

<bound method PCA.score of PCA(copy=True, iterated_power='auto', n_components=0.95, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)>